### ISSUE TITLE
Add the ability to manage Seed transactions from Spring & Spring batch support 

### ISSUE THREAD

**Issue by adrienlauer** [seedstack/seed-spring-extensions#1]
_From @Red1L on March 27, 2015 11:23_

We need to provide an implementation of  the Spring `PlatformTransactionManager` interface.
To do so we will probably have to inject and use a SEED `TransactionHandler`.

_Copied from original issue: seedstack/seed#19_

**Comment by TheBigAleski** [comment]
Hi,

Any news regarding this matter ?
As already explained, this really curbs Spring Batch in here...

Thanks and regards,
Alexis LEGROS.

**Comment by adrienlauer** [comment]
We started to work on this in July but unfortunately this effort was temporarily halted. I'm rescheduling the issue for version 2.1 which will be part of the 15.11 distribution in November.

**Comment by TheBigAleski** [comment]
Thanks for the update, we eagerly look forward to this fix.

**Comment by adrienlauer** [comment]
This will be released in the 2.2.0 version of spring bridge addon which will be included in the 15.11 distribution, due in a few days.

**Comment by TheBigAleski** [comment]
Thanks for these great news, we can't wait to benefit from this fix :smiley:
